<a href="https://colab.research.google.com/github/IGDeft/Cblol-Tigrinho/blob/main/CblolTigrinho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd

tabela = pd.read_csv("2025_LoL_esports_match_data_from_OraclesElixir.csv")
display(tabela)

C:\Users\lucas\AppData\Local\Temp\ipykernel_4664\3215500760.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela = pd.read_csv("2025_LoL_esports_match_data_from_OraclesElixir.csv")

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,200.0,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,157.0,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,241.0,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,257.0,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,20.0,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120631,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,224.0,-125.0,-500.0,-32.0,8.0,5.0,2.0,4.0,4.0,1.0
120632,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,221.0,-541.0,513.0,5.0,0.0,7.0,2.0,2.0,4.0,2.0
120633,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,31.0,1255.0,2399.0,17.0,1.0,9.0,1.0,1.0,1.0,4.0
120634,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,874.0,-4102.0,-8294.0,-66.0,8.0,18.0,13.0,13.0,34.0,8.0
120635,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,808.0,4102.0,8294.0,66.0,13.0,34.0,8.0,8.0,18.0,13.0

In [77]:
print(tabela['league'].unique())
print()
print(tabela.columns.tolist())

['LFL2' 'LPL' 'LCKC' 'LVP SL' 'LCK' 'NLC' 'LCP' 'LEC' 'HLL' 'PRM' 'LFL'
 'LIT' 'TCL' 'HW' 'LJL' 'LTA S' 'LTA N' 'RL' 'NEXO' 'CD' 'EBL' 'PCS' 'ROL'
 'LPLOL' 'AL' 'LTA' 'VCS' 'FST' 'EM' 'LRS' 'LRN' 'NACL' 'LAS' 'HC' 'PRMP'
 'HM' 'CT' 'Asia Master' 'MSI' 'EWC' 'WLDs' 'ASI' 'IC' 'KeSPA' 'DCup']

['gameid', 'datacompleteness', 'url', 'league', 'year', 'split', 'playoffs', 'date', 'game', 'patch', 'participantid', 'side', 'position', 'playername', 'playerid', 'teamname', 'teamid', 'firstPick', 'champion', 'ban1', 'ban2', 'ban3', 'ban4', 'ban5', 'pick1', 'pick2', 'pick3', 'pick4', 'pick5', 'gamelength', 'result', 'kills', 'deaths', 'assists', 'teamkills', 'teamdeaths', 'doublekills', 'triplekills', 'quadrakills', 'pentakills', 'firstblood', 'firstbloodkill', 'firstbloodassist', 'firstbloodvictim', 'team kpm', 'ckpm', 'firstdragon', 'dragons', 'opp_dragons', 'elementaldrakes', 'opp_elementaldrakes', 'infernals', 'mountains', 'clouds', 'oceans', 'chemtechs', 'hextechs', 'dragons (type unknown)', 'elders', 'opp_elders', 'firstherald', 'heralds', 'opp_heralds', 'void_grubs', 'opp_void_grubs', 'firstbaron', 'barons', 'opp_barons', 'atakhans', 'opp_atakhans', 'firsttower', 'towers', 'opp_towers', 'firstmidtower', 'firsttothreetowers', 'turretplates', 'opp_turretplates', 'inhibitors', 'opp_inhibitors', 'damagetochampions', 'dpm', 'damageshare', 'damagetakenperminute', 'damagemitigatedperminute', 'damagetotowers', 'wardsplaced', 'wpm', 'wardskilled', 'wcpm', 'controlwardsbought', 'visionscore', 'vspm', 'totalgold', 'earnedgold', 'earned gpm', 'earnedgoldshare', 'goldspent', 'gspd', 'gpr', 'total cs', 'minionkills', 'monsterkills', 'monsterkillsownjungle', 'monsterkillsenemyjungle', 'cspm', 'goldat10', 'xpat10', 'csat10', 'opp_goldat10', 'opp_xpat10', 'opp_csat10', 'golddiffat10', 'xpdiffat10', 'csdiffat10', 'killsat10', 'assistsat10', 'deathsat10', 'opp_killsat10', 'opp_assistsat10', 'opp_deathsat10', 'goldat15', 'xpat15', 'csat15', 'opp_goldat15', 'opp_xpat15', 'opp_csat15', 'golddiffat15', 'xpdiffat15', 'csdiffat15', 'killsat15', 'assistsat15', 'deathsat15', 'opp_killsat15', 'opp_assistsat15', 'opp_deathsat15', 'goldat20', 'xpat20', 'csat20', 'opp_goldat20', 'opp_xpat20', 'opp_csat20', 'golddiffat20', 'xpdiffat20', 'csdiffat20', 'killsat20', 'assistsat20', 'deathsat20', 'opp_killsat20', 'opp_assistsat20', 'opp_deathsat20', 'goldat25', 'xpat25', 'csat25', 'opp_goldat25', 'opp_xpat25', 'opp_csat25', 'golddiffat25', 'xpdiffat25', 'csdiffat25', 'killsat25', 'assistsat25', 'deathsat25', 'opp_killsat25', 'opp_assistsat25', 'opp_deathsat25']

In [78]:
tabela_lta_sul = tabela[tabela['league'] == "LTA S"].copy()
display(tabela_lta_sul)

tabela_relev = [

    # Identificação Jogo

    'gameid', "split", "game", "patch", "date", "playoffs", "position",
    "result",
    # Jogador/Time
    "playername", "teamname", "participantid", "playerid", "kills", "deaths",
    "assists", "teamkills", "teamdeaths", "earnedgoldshare", "damageshare",

    # Pick e Ban
    "ban1", "ban2", "ban3", "ban4", "ban5", "pick1", "pick2", "pick3", "pick4",
    'pick5', "firstPick", "champion",

    # Objetivos

    "void_grubs", "towers", "turretplates", "dragons",

    # Ritmo de Jogo

    "firsttower", "firstblood", "firstdragon", "firstbaron", "firstherald",
    "gamelength", "csdiffat10", "xpdiffat10", "golddiffat10",
    "csdiffat15", "xpdiffat15", "golddiffat15",
    "team kpm", "ckpm", "cspm",
]

tabela_final = tabela_lta_sul[tabela_relev].copy()
tabela_final["gamelength"] = pd.to_timedelta(tabela_final["gamelength"], unit = 's')
tabela_final["gamelength"] = (tabela_final["gamelength"] + pd.to_datetime("1970-01-01")).dt.strftime("%H:%M:%S")

display(tabela_final)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
3972,LOLTMNT01_191597,complete,NaN,LTA S,2025,Split 1,0,2025-01-25 16:17:11,1,15.02,...,268.0,-1228.0,-435.0,-55.0,1.0,3.0,1.0,0.0,2.0,0.0
3973,LOLTMNT01_191597,complete,NaN,LTA S,2025,Split 1,0,2025-01-25 16:17:11,1,15.02,...,171.0,-127.0,-730.0,-11.0,2.0,5.0,2.0,0.0,5.0,2.0
3974,LOLTMNT01_191597,complete,NaN,LTA S,2025,Split 1,0,2025-01-25 16:17:11,1,15.02,...,221.0,-568.0,1370.0,0.0,2.0,4.0,1.0,4.0,1.0,2.0
3975,LOLTMNT01_191597,complete,NaN,LTA S,2025,Split 1,0,2025-01-25 16:17:11,1,15.02,...,207.0,-106.0,328.0,7.0,2.0,5.0,1.0,2.0,3.0,2.0
3976,LOLTMNT01_191597,complete,NaN,LTA S,2025,Split 1,0,2025-01-25 16:17:11,1,15.02,...,30.0,588.0,1672.0,-5.0,1.0,7.0,1.0,0.0,5.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114655,LOLTMNT03_306244,complete,NaN,LTA S,2026,NaN,0,2025-10-08 17:48:17,3,15.19,...,178.0,3922.0,5696.0,52.0,6.0,10.0,1.0,1.0,5.0,6.0
114656,LOLTMNT03_306244,complete,NaN,LTA S,2026,NaN,0,2025-10-08 17:48:17,3,15.19,...,175.0,4343.0,3750.0,38.0,10.0,10.0,2.0,3.0,2.0,8.0
114657,LOLTMNT03_306244,complete,NaN,LTA S,2026,NaN,0,2025-10-08 17:48:17,3,15.19,...,36.0,840.0,2219.0,-9.0,0.0,23.0,3.0,1.0,5.0,6.0
114658,LOLTMNT03_306244,complete,NaN,LTA S,2026,NaN,0,2025-10-08 17:48:17,3,15.19,...,875.0,-16606.0,-21001.0,-171.0,9.0,18.0,33.0,33.0,68.0,9.0
114659,LOLTMNT03_306244,complete,NaN,LTA S,2026,NaN,0,2025-10-08 17:48:17,3,15.19,...,704.0,16606.0,21001.0,171.0,33.0,68.0,9.0,9.0,18.0,33.0

,gameid,split,game,patch,date,playoffs,position,result,playername,teamname,...,gamelength,csdiffat10,xpdiffat10,golddiffat10,csdiffat15,xpdiffat15,golddiffat15,team kpm,ckpm,cspm
3972,LOLTMNT01_191597,Split 1,1,15.02,2025-01-25 16:17:11,0,top,1,Robo,LOUD,...,00:36:33,-13.0,-6.0,-411.0,-27.0,-331.0,-390.0,0.5198,0.7661,6.9767
3973,LOLTMNT01_191597,Split 1,1,15.02,2025-01-25 16:17:11,0,jng,1,Wiz,LOUD,...,00:36:33,-9.0,-375.0,125.0,-4.0,-441.0,-232.0,0.5198,0.7661,5.7182
3974,LOLTMNT01_191597,Split 1,1,15.02,2025-01-25 16:17:11,0,mid,1,tinowns,LOUD,...,00:36:33,-3.0,463.0,-367.0,-9.0,262.0,-1699.0,0.5198,0.7661,7.6881
3975,LOLTMNT01_191597,Split 1,1,15.02,2025-01-25 16:17:11,0,bot,1,Route,LOUD,...,00:36:33,-1.0,-563.0,-610.0,13.0,-206.0,-471.0,0.5198,0.7661,7.7975
3976,LOLTMNT01_191597,Split 1,1,15.02,2025-01-25 16:17:11,0,sup,1,Winsome,LOUD,...,00:36:33,-4.0,-180.0,-33.0,-4.0,2.0,-7.0,0.5198,0.7661,0.8755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114655,LOLTMNT03_306244,NaN,3,15.19,2025-10-08 17:48:17,0,mid,1,Keine,Isurus,...,00:24:24,18.0,580.0,733.0,23.0,372.0,777.0,1.3525,1.7213,9.4262
114656,LOLTMNT03_306244,NaN,3,15.19,2025-10-08 17:48:17,0,bot,1,Snaker,Isurus,...,00:24:24,1.0,634.0,742.0,12.0,744.0,603.0,1.3525,1.7213,8.7295
114657,LOLTMNT03_306244,NaN,3,15.19,2025-10-08 17:48:17,0,sup,1,Ackerman,Isurus,...,00:24:24,-4.0,-134.0,-43.0,-5.0,-643.0,-724.0,1.3525,1.7213,1.1066
114658,LOLTMNT03_306244,NaN,3,15.19,2025-10-08 17:48:17,0,team,0,NaN,Alpha7 Esports,...,00:24:24,-42.0,-1717.0,-2591.0,-63.0,-2052.0,-3049.0,0.3689,1.7213,28.8525
114659,LOLTMNT03_306244,NaN,3,15.19,2025-10-08 17:48:17,0,team,1,NaN,Isurus,...,00:24:24,42.0,1717.0,2591.0,63.0,2052.0,3049.0,1.3525,1.7213,35.8607

In [79]:
# Global pIcks

tabela_players = tabela_final[tabela_final['position']!= "team"]
champion_global = tabela_players['champion'].value_counts()
print(champion_global.head(20))

# Global Bans

tabela_team = tabela_final[tabela_final['position'] == "team"]

bans_global = pd.concat([
    tabela_team["ban1"],
    tabela_team['ban2'],
    tabela_team['ban3'],
    tabela_team['ban4'],
    tabela_team['ban5']
])
print("-" * 20)
print("Bans")

print(bans_global.value_counts().head(20))

# Pick Rate

total_jogos = tabela_team['gameid'].nunique()
pick_rate = (champion_global / total_jogos) * 100

print("-" * 20)
print("Pick Rate")

print(pick_rate.head(20).round(2))

# Ban Rate

ban_rate = (bans_global.value_counts()/ total_jogos) * 100

print("-" * 20)
print("Ban Rate")
print(ban_rate.head(20).round(2))

champion
Rell            65
Xin Zhao        65
Alistar         60
Rumble          59
Rakan           59
Vi              55
Ambessa         52
Corki           51
Sejuani         51
Ezreal          49
Ahri            49
Taliyah         48
Nautilus        46
Miss Fortune    45
Azir            42
Gwen            41
Renekton        39
Neeko           39
Sion            38
Aurora          37
Name: count, dtype: int64
--------------------
Bans
Varus       127
Gwen         93
Yone         83
Kalista      80
Azir         73
Taliyah      60
Rumble       60
Pantheon     57
Neeko        56
Vi           55
Sejuani      53
Jayce        53
Skarner      50
Lucian       46
Poppy        46
Jax          45
Ashe         45
Aurora       44
Ambessa      42
Wukong       42
Name: count, dtype: int64
--------------------
Pick Rate
champion
Rell            29.28
Xin Zhao        29.28
Alistar         27.03
Rumble          26.58
Rakan           26.58
Vi              24.77
Ambessa         23.42
Corki           22.97
Sejuani         22.97
Ezreal          22.07
Ahri            22.07
Taliyah         21.62
Nautilus        20.72
Miss Fortune    20.27
Azir            18.92
Gwen            18.47
Renekton        17.57
Neeko           17.57
Sion            17.12
Aurora          16.67
Name: count, dtype: float64
--------------------
Ban Rate
Varus       57.21
Gwen        41.89
Yone        37.39
Kalista     36.04
Azir        32.88
Taliyah     27.03
Rumble      27.03
Pantheon    25.68
Neeko       25.23
Vi          24.77
Sejuani     23.87
Jayce       23.87
Skarner     22.52
Lucian      20.72
Poppy       20.72
Jax         20.27
Ashe        20.27
Aurora      19.82
Ambessa     18.92
Wukong      18.92
Name: count, dtype: float64

In [80]:
df_meta = pd.DataFrame({
    "pick_rate": pick_rate,
    "ban_rate": ban_rate
}).fillna(0)

df_meta['presence'] = df_meta["pick_rate"] + df_meta["ban_rate"]
df_meta = df_meta.sort_values(by="presence", ascending = False)
print(df_meta.head(50).round(2))

              pick_rate  ban_rate  presence
Varus             15.32     57.21     72.52
Gwen              18.47     41.89     60.36
Rumble            26.58     27.03     53.60
Azir              18.92     32.88     51.80
Vi                24.77     24.77     49.55
Taliyah           21.62     27.03     48.65
Yone              10.81     37.39     48.20
Sejuani           22.97     23.87     46.85
Alistar           27.03     15.77     42.79
Neeko             17.57     25.23     42.79
Kalista            6.31     36.04     42.34
Ambessa           23.42     18.92     42.34
Pantheon          14.86     25.68     40.54
Xin Zhao          29.28      9.46     38.74
Skarner           15.77     22.52     38.29
Ezreal            22.07     16.22     38.29
Jayce             13.51     23.87     37.39
Nautilus          20.72     16.22     36.94
Miss Fortune      20.27     16.67     36.94
Rakan             26.58      9.91     36.49
Aurora            16.67     19.82     36.49
Ashe              15.32     20.27     35.59
Wukong            16.22     18.92     35.14
Jax               14.41     20.27     34.68
Ahri              22.07     11.71     33.78
Rell              29.28      4.05     33.33
Poppy             12.61     20.72     33.33
Lucian            12.16     20.72     32.88
Corki             22.97      9.46     32.43
Kai'Sa            16.22     14.86     31.08
Ryze              14.41     13.06     27.48
Braum             14.86     12.61     27.48
Renekton          17.57      9.91     27.48
Orianna           12.16     14.41     26.58
Nocturne           8.56     17.12     25.68
K'Sante           14.41     10.36     24.77
Maokai            10.81     13.96     24.77
Sylas             11.71     12.16     23.87
Trundle           10.36     13.06     23.42
Sion              17.12      5.86     22.97
Annie             12.16     10.36     22.52
Akali             11.26     10.81     22.07
Galio             13.06      8.56     21.62
Jhin              15.32      5.41     20.72
Xayah             11.26      9.01     20.27
Jarvan IV          7.66     11.71     19.37
Leona             12.61      5.86     18.47
Viktor            10.36      6.76     17.12
Yunara             7.66      9.46     17.12
Sivir             10.36      6.31     16.67

In [81]:
print(tabela_lta_sul['teamname'].unique())

['LOUD' 'paiN Gaming' 'Vivo Keyd Stars' 'Leviatan' 'Isurus Estral' 'FURIA'
 'RED Canids' 'Fluxo W7M' 'Isurus' 'Flamengo MDL' 'Sicar Esports'
 'Farenvehn' 'Alpha7 Esports']

In [82]:
def gerar_df_time(nome_time):
    tabela_equipes = tabela_final[tabela_final["teamname"] == nome_time].copy()
    if tabela_equipes.empty:
        print(f"Time {nome_time} não foi encontrado.")
        return None
    
    picks = tabela_equipes['champion'].value_counts()

    tabela_team = tabela_equipes[tabela_equipes["position"] == "team"]

    bans = pd.concat([
        tabela_team["ban1"],
        tabela_team["ban2"],
        tabela_team["ban3"],
        tabela_team["ban4"],
        tabela_team["ban5"]
    ]).value_counts()

    total_jogos = tabela_team["gameid"].nunique()

    if total_jogos == 0:
        print(f"Time {nome_time} não tem jogos validos")
        return None
    
    df_time = pd.DataFrame({
        "picks" : picks,
        "bans" : bans
    }).fillna(0)

    df_time["pick_rate"] = (df_time["picks"] / total_jogos) * 100
    df_time["ban_rate"] = (df_time["bans"] / total_jogos) * 100
    df_time["presenca"]= (df_time["pick_rate"] + df_time["ban_rate"])

    df_time = df_time.sort_values(by = "presenca", ascending = False)
    return df_time.round(2)

In [83]:
time1 = input("1 time: ")
time2 = input("2 time: ")

df_time1 = gerar_df_time(time1)
df_time2 = gerar_df_time(time2)

if df_time1 is not None and df_time2 is not None:
    print(time1)
    display(df_time1.head(10))
    print(time2)
    display(df_time2.head(10))

FURIA

          picks  bans  pick_rate  ban_rate  presenca
Yone        0.0  28.0       0.00     51.85     51.85
Varus       5.0  15.0       9.26     27.78     37.04
Azir        6.0  14.0      11.11     25.93     37.04
Skarner    10.0   6.0      18.52     11.11     29.63
Kalista     0.0  15.0       0.00     27.78     27.78
Taliyah     8.0   7.0      14.81     12.96     27.78
Gwen        6.0   8.0      11.11     14.81     25.93
Vi          3.0  10.0       5.56     18.52     24.07
Xin Zhao   10.0   3.0      18.52      5.56     24.07
Nautilus    6.0   7.0      11.11     12.96     24.07

LOUD

          picks  bans  pick_rate  ban_rate  presenca
Yone        2.0  30.0       3.64     54.55     58.18
Varus       3.0  17.0       5.45     30.91     36.36
Pantheon    5.0  12.0       9.09     21.82     30.91
Jayce       1.0  16.0       1.82     29.09     30.91
Sejuani     8.0   9.0      14.55     16.36     30.91
Azir        6.0   9.0      10.91     16.36     27.27
Gwen        3.0  12.0       5.45     21.82     27.27
Kalista     1.0  13.0       1.82     23.64     25.45
Alistar    10.0   3.0      18.18      5.45     23.64
Taliyah     6.0   5.0      10.91      9.09     20.00

In [84]:
def sugeriPicks(time1, bansTime1, picksTime1, time2, bansTime2, picksTime2, picks):
    df = gerar_df_time(time1)
    
    proibidos = list(bansTime1) + list(bansTime2) + list(picks)

    df_filtrado = df[~df.index.astype(str).isin(proibidos)]

    if df_filtrado.empty:
        return "Não existe mais personagens disponíveis"
    
    return df_filtrado.sort_values(by = "pick_rate", ascending = False).index[0]

def sugeriBans(time1, bansTime1, picksTime1, time2, bansTime2, picksTime2, picks):
    df = gerar_df_time(time1)
    proibidos = list(bansTime1) + list(bansTime2) + list(picks)

    df_filtrado = df[~df.index.astype(str).isin(proibidos)]

    if df_filtrado.empty:
        return "Não existe mais personagens disponíveis"
    
    return df_filtrado.sort_values(by = "ban_rate", ascending = False).index[0]

def gerar_Dna_Automatico(df_completo):
    contagem = df_completo.groupby(["champion", "position"]).size().unstack(fill_value = 0)
    dna_percentual = contagem.div(contagem.sum(axis = 1), axis = 0)

    return dna_percentual.to_dict(orient = "index")

dna_campeoes = gerar_Dna_Automatico(tabela_final)

In [85]:
def ordemPicksBans(timeFP, timeLP, jogos, picks=None):

  if picks is None:
    picks = []

  picksFP, bansFP = [], []
  picksLP, bansLP = [], []

  bans = []

  for _ in range(3):
    ban = sugeriBans(timeFP, bansFP, picksFP, timeLP, bansLP, picksLP, picks)
    bans.append(ban)
    bansFP.append(ban)

    ban = sugeriBans(timeLP, bansLP, picksLP, timeFP, bansFP, picksFP, picks)
    bans.append(ban)
    bansLP.append(ban)

  ordem = [timeFP, timeLP, timeLP, timeFP, timeFP, timeLP]

  for time_atual in ordem:
    if time_atual == timeFP:
      champ = sugeriPicks(timeFP, bansFP, picksFP, timeLP, bansLP, picksLP, picks)
      picksFP.append(champ)
    else:
      champ = sugeriPicks(timeLP, bansLP, picksLP, timeFP, bansFP, picksFP, picks)
      picksLP.append(champ)

    picks.append(champ)

  for _ in range(2):
    ban = sugeriBans(timeLP, bansLP, picksLP, timeFP, bansFP, picksFP, picks)
    bans.append(ban)
    bansLP.append(ban)

    ban = sugeriBans(timeFP, bansFP, picksFP, timeLP, bansLP, picksLP, picks)
    bans.append(ban)
    bansFP.append(ban)

  ordem2 = [timeLP, timeFP, timeFP, timeLP]

  for time_atual in ordem2:

    if time_atual == timeFP:
      champ = sugeriPicks(timeFP, bansFP, picksFP, timeLP, bansLP, picksLP, picks)
      picksFP.append(champ)
    else:
      champ = sugeriPicks(timeLP, bansLP, picksLP, timeFP, bansFP, picksFP, picks)
      picksLP.append(champ)

    picks.append(champ)

  jogo_atual = [picksFP, bansFP, picksLP, bansLP]

  if jogos > 1:
    return [jogo_atual] + ordemPicksBans(timeFP, timeLP, jogos-1, picks)
  
  return [jogo_atual]

<function ordemPicksBans at 0x000001FF462B3F60>

In [86]:
df_agrupados = tabela_final.groupby([
    "gameid", "teamname", "result", "gamelength",
    "ban1", "ban2", "ban3", "pick1", "pick2",
    "pick3", "ban4", "ban5", "pick4", "pick5"
]).size().reset_index() 

df_confronto = pd.merge(df_agrupados, df_agrupados, on = "gameid", suffixes = ("_time1", "_time2"))
df_confronto = df_confronto[df_confronto["teamname_time1"] != df_confronto["teamname_time2"]]
df_confronto = df_confronto.drop_duplicates(subset = ["gameid"], keep = "first")

display(df_confronto)

,gameid,teamname_time1,result_time1,gamelength_time1,ban1_time1,ban2_time1,ban3_time1,pick1_time1,pick2_time1,pick3_time1,...,ban2_time2,ban3_time2,pick1_time2,pick2_time2,pick3_time2,ban4_time2,ban5_time2,pick4_time2,pick5_time2,0_time2
1,LOLTMNT01_191597,LOUD,1,00:36:33,Yone,Maokai,Ambessa,K'Sante,Ezreal,Azir,...,Kalista,Varus,Orianna,Nocturne,Gnar,Xin Zhao,Leona,Corki,Alistar,1
5,LOLTMNT01_191624,LOUD,0,00:32:33,Skarner,Kalista,Yone,Jayce,Xin Zhao,Viktor,...,Nidalee,Ambessa,Maokai,Ashe,Braum,Rakan,Lulu,Jax,Ahri,1
9,LOLTMNT01_191692,Leviatan,0,00:24:48,Skarner,Nocturne,Vi,Wukong,Aurora,Jayce,...,Ashe,Zyra,Varus,Azir,Ambessa,Zeri,Rell,Braum,Viego,1
14,LOLTMNT01_192707,LOUD,0,00:34:40,Yone,Xayah,Caitlyn,Ambessa,Vi,Kai'Sa,...,Skarner,Varus,Renekton,Wukong,Tristana,Leona,Nautilus,Rakan,Swain,1
18,LOLTMNT01_192721,Leviatan,1,00:27:25,Skarner,Nocturne,Ambessa,Maokai,Corki,Gnar,...,Kalista,Zyra,K'Sante,Sejuani,Ezreal,Aurora,Rell,Alistar,Viktor,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
854,LOLTMNT06_121140,FURIA,1,00:35:11,Varus,Caitlyn,Lucian,Wukong,Taliyah,Ezreal,...,Ashe,Corki,Vi,Xayah,Rakan,Karma,Nautilus,Rumble,Galio,1
858,LOLTMNT06_121226,LOUD,1,00:30:17,Yone,Sejuani,Taliyah,Vi,Ahri,Jax,...,Varus,Azir,Xin Zhao,Miss Fortune,K'Sante,Braum,Kalista,Veigar,Rell,1
862,LOLTMNT06_121228,LOUD,0,00:36:05,Yone,Varus,Sejuani,Pantheon,Taliyah,Gnar,...,Kalista,Rumble,Gwen,Naafiri,Annie,Ashe,Kai'Sa,Ezreal,Poppy,1
866,LOLTMNT06_121232,LOUD,0,00:30:08,Yone,Lillia,Ivern,Sejuani,Corki,Nautilus,...,Azir,Renekton,Ashe,Nidalee,Braum,Syndra,Olaf,Ryze,Fiora,1
870,LOLTMNT06_121241,Leviatan,0,00:31:12,Vi,Pantheon,Nautilus,Gwen,Naafiri,Ahri,...,Varus,Lucian,Rumble,Xin Zhao,Annie,Kalista,Ashe,Ezreal,Poppy,1